Dev
DanilPorkchop15/ts-exersices-ws pull request #1
Opened 2024-09-17 06:44 UTC by DanilPorkchop15

2024-09-23 15:21 UTC, mordvinsky requested changes

2024-09-23 15:21 UTC, mordvinx commented on 1.ts
> +const actionMap: Array<`${Action}`> = [
Молодец

2024-09-23 15:21 UTC, mordvinx commented on 1.ts
> +interface IUser {
Достаточно User, не пиши I в начале интерфейсов

2024-09-23 15:21 UTC, mordvinx commented on 1.ts
> +interface IFuncMap {
I

2024-09-23 15:21 UTC, mordvinx commented on 2.ts
> +  return { z: 2 } as TReturn<T>;
as это матерное слово в TS, в таком контексте его использовать нельзя. 

Еще нельзя использовать ! - non null assertion

И то и другое нужно использовать тогда, когда по-другому никак нельзя.

Здесь ты можешь указать возвращаемый тип функции и все будет работать нормально

2024-09-23 15:21 UTC, mordvinx commented on 2.ts
> +function f2(arg: number | string) {
Возвращаемый тип нужно указать явно

2024-09-24 06:35 UTC, DanilPorkchop15 commented on 2.ts
> +  return { z: 2 } as TReturn<T>;
не работает без приведения через as, даже если возвращаемый тип указан,
поведение функции  с as верное и подсказки правильно предлагаются

2024-09-29 15:08 UTC, merged